# This configuration file is for the **development** setup.
version: "2.2"
x-kubespider: &kubespider
  build:
    context: .
    # args:
  volumes:
    - ${KUBESPIDER_HOME}/kubespider/.config:/app/.config
    - ./kubespider:/app/kubespider
  # env_file:
  #   - .env

services:
  kubespider:
    <<: *kubespider
    command: dev_server
    environment:
      - PUID=${UID}
      - PGID=${GID}
    network_mode: host
    # environment:
    
